### ISSUE TITLE
How to create nested models?

### ISSUE THREAD

**Issue by Codeluck** [charto/classy-mst#1]
Hi there. I am just curious about creating nested models using classy-mst. Say I have a Page which a result of composing data and code using mst call. I wanna Page to store an array of elements which are a set of Element model. Element is a composition of ElementData and ElementCode. How could I define that structure using classy-mst? I got an error like this when trying to run my project:

![image](https://user-images.githubusercontent.com/6416507/33699819-07101512-db48-11e7-8b79-297309f3014c.png)
An here is my code:
```typescript
const ElementData = shim(types.model("Element", {props});
class ElementCode extends ElementData {
    @action
     someElementAction() {
        ...
     }
}
export const Element = mst(ElementData, ElementCode);

const PageData = shim(types.model("Page", {elements:types.array(Element)});
class PageCode extends PageData {
    @action
    someAction() {
        ...
    }
}
export const Page = mst(PageData,PageCode);
```

**Comment by Codeluck** [comment]
Sorry, my bad. I accidentally swapped PageData and PageCode in mst call. It works fine now. Thank you for awesome package. It helps me a lot in structuring my code.

**Comment by jjrv** [comment]
Thanks for the encouraging words! Nice to hear that this package has been useful.
