### ISSUE TITLE
Recursive type maximum call stack exceeded

### ISSUE THREAD

**Issue by Amareis** [charto/classy-mst#11]
This code (in pure mst) works well:
```js
const LateMessage = types.late((): IAnyModelType => Message)

export const Message = types.model('Message', {
    id: types.identifier,
    quoted: types.maybeNull(LateMessage),
})
```

But this code is failing (when creating from snapshot):
```js
const LateMessage = types.late((): IAnyModelType => Message)

const MessageData = types.model('MessageData', {
    id: types.identifier,
    quoted: types.maybeNull(LateMessage),
})

class MessageCode extends shim(MessageData) {
}

export const Message = mst(MessageCode, MessageData, 'Message')
```
![image](https://user-images.githubusercontent.com/4806617/46479969-a8f9bc80-c809-11e8-862d-710b8ebacc08.png)

**Comment by Amareis** [comment]
@jjrv can you fix it or explain how it can be fixed in classy-mst?

**Comment by Amareis** [comment]
But with types.late typescript don't complain about circular type. There is only runtime error because of incorrect handling of maybeNull, I think.

**Comment by jjrv** [comment]
I found that a slightly improved fix to #8 also would fix this, however while disabling polymorphism support for the `Message` type (so you cannot then inherit from it, serialize to a snapshot and correctly deserialize different types of messages).

The diff of `classy-mst.ts` is:

```TypeScript
-       let Model = Data.preProcessSnapshot(
-               // Instantiating a union of models requires a snapshot.
-               (snap: any) => snap || {}
-       ).postProcessSnapshot((snap: any) => {
+       let Model = Data.postProcessSnapshot((snap: any) => {

-       return(polymorphic(Code, Model, modelName));
+       return(Model as any);
```

Can you test it? I'll need to add a new options object to allow toggling this fix on/off.

**Comment by jjrv** [comment]
Actually it seems a `mobx-state-tree` bug has been fixed and that `preProcessSnapshot` hook is no longer needed. Meanwhile it actually triggers this bug... For some reason simply removing the hook fixes this, and as you see the hook does nothing but ensures there is a snapshot, because without one creating union instances used to fail.

**Comment by Amareis** [comment]
Sooo, what is the final fix? Just remove `preProcessSnapshot` form `classy-mst.ts`?

**Comment by jjrv** [comment]
Try and see if it works for you. Seems to still cause some tests to fail. I'll fix this one way or another and release a new version. Disabling polymorphism for the type may still be necessary.

**Comment by Amareis** [comment]
Ok, i'll try it.

**Comment by Amareis** [comment]
Yeah, removing of `preProcessSnapshot` did the trick!

Anyway, I alredy refactor my `Message` type to use `types.reference` to quoted, so it working without fix, but thank you for help, I'll wait for the release.

**Comment by jjrv** [comment]
OK, version 3.5.0 is out. It now works with a flag:

```TypeScript
export const Message = mst(MessageCode, MessageData, 'Message', { sealed: true })
```

**Comment by jjrv** [comment]
Thanks for reporting!
