### ISSUE TITLE
Compatibility with mst 3.7.1

### ISSUE THREAD

**Issue by Amareis** [charto/classy-mst#13]
In https://github.com/mobxjs/mobx-state-tree/pull/1043 there is significantly reworked inner types. Now classy-mst doesn't work with newest mst and typescript (ts cannot find fields from `Data` class on `Code` class)

**Comment by Peterabsolon** [comment]
Hijacking this to mention that I just found this project and I really dig it. Awesome work. Looking forward to using it

**Comment by jjrv** [comment]
Should be fixed in new version 3.7.0 of this package, can you verify?

**Comment by Amareis** [comment]
Yeah, it working, thank you!
