### ISSUE TITLE
Inheritance example does not seem to work

### ISSUE THREAD

**Issue by mindaugasnakrosis** [charto/classy-mst#16]
Provided inheritance example does not seem to work:

    [mobx-state-tree] Cannot modify 'SpecialTodo@<root>', the object is protected and can only be modified by using an action.

      10 |      @action
      11 |      toggle() {
    > 12 |              log.debug('Toggled ' + (++this.count) + ' times!');
         |                                             ^
      13 |              super.toggle();
      14 |      }
      15 | }

Code:

```
const TodoData = types.model({
	title: types.string,
	done: false
});
class TodoCode extends shim(TodoData) {
	@action
	toggle() {
		this.done = !this.done;
	}
}
const Todo = mst(TodoCode, TodoData, 'Todo');

const SpecialTodoData = Todo.props({
	count: 0
});
class SpecialTodoCode extends shim(SpecialTodoData, Todo) {
	@action
	toggle() {
		log.debug('Toggled ' + (++this.count) + ' times!');
		super.toggle();
	}
}
const SpecialTodo = mst(SpecialTodoCode, SpecialTodoData, 'SpecialTodo');

const specialTodo = SpecialTodo.create({ title: 'todo' });
specialTodo.toggle(); // error

```

**Comment by Elminday** [comment]
@jjrv

**Comment by jjrv** [comment]
I just replaced `test/test.ts` with your code locally, changed `log.debug` to `console.log` and added the following on top:

```TypeScript
import { types } from 'mobx-state-tree';
import { mst, shim, action } from '..';
```

It seems to work fine now (`npm test` runs successfully with your code).
