### ISSUE TITLE
inheritance types after recent typescript/vsc updates

### ISSUE THREAD

**Issue by ksjogo** [charto/classy-mst#17]
On the latest typescript and vsc versions only types from the current mst class are inferred, and not from parent shims as well.

**Comment by dsabanin** [comment]
I didn't notice any problems with typescript 3.4.1 update, but updating mobx-state-tree to any version higher than 3.11.0 breaks inheritance for me like you said.

**Comment by jjrv** [comment]
Sorry for the delay. Now `classy-mst` is updated and released for mst 3.14.0. Hope it works for you.
