### ISSUE TITLE
Views and getters don't work

### ISSUE THREAD

**Issue by aksonov** [charto/classy-mst#4]
```
/Users/aksonov/Documents/wocky-client/node_modules/classy-mst/dist/classy-mst.js:48
    var Model = Data.views(function (self) { return bindMembers(self, true, Code.prototype); }).actions(function (self) { return bindMembers(self, true, Code.prototype.$actions || []); }).volatile(function (self) { return bindMembers(self, false, new Code()); });
                     ^
TypeError: Data.views is not a function
```

Code is following:
```
export class RosterCode extends RosterModel {
  get sortedRoster() {
    return this.roster.filter(x => x.handle).sort((a, b) => {
      return a.handle.toLocaleLowerCase().localeCompare(b.handle.toLocaleLowerCase())
    })
  }
  get all() {
    return this.sortedRoster.filter(x => !x.isBlocked)
  }
  get followers() {
    return this.sortedRoster.filter(x => !x.isBlocked && x.isFollower)
  }
  get following() {
    return this.sortedRoster.filter(x => !x.isBlocked && x.isFollowed)
  }
  @action
  sendPresence() {
    const {provider} = getEnv(this as IStateTreeNode)
    provider.sendPresence()
  }
}
```

**Comment by jjrv** [comment]
You need:

```TypeScript
export class RosterCode extends shim(RosterModel) {
```

The `shim` is needed for the TypeScript compiler to believe that a class extending `RosterModel` is a `mobx-state-tree` model, and also for full ES6 compatibility (extending something that isn't a real class will break if in the future you target ES6 in browsers, or transpile using Babel).

**Comment by aksonov** [comment]
Yes, I did `RosterModel = shim(types.model(...)`

**Comment by jjrv** [comment]
Then the `mst` function might fail, because it wants the original model without the `shim`wrapper.

**Comment by jjrv** [comment]
It also doesn't currently handle getters. I'll add support for them...

**Comment by jjrv** [comment]
OK done, if you run into issues with the getter not getting called please try the `develop` branch. I need to add more tests before releasing it. Should be done soon.

**Comment by aksonov** [comment]
Thanks, you are right about failing of MST function. Will try develop branch too, good job!

**Comment by aksonov** [comment]
I just tried develop branch, getters are still not visible

**Comment by aksonov** [comment]
Non-getters doesn't work too?
```
import {types} from 'mobx-state-tree'
import {mst, shim, action} from 'classy-mst'

const TodoData = types.model({
  title: types.string,
  done: false
})

class TodoCode extends shim(TodoData) {
  isDone() {
    return this.done
  }
  @action
  toggle() {
    this.done = !this.done
  }
}

const Todo = mst(TodoCode, TodoData)

describe('hello', () => {
  it('first', done => {
    const t = Todo.create({title: 'nice'})
    t.toggle()
    console.log(t.isDone())
    done()
  })
})

```

**Comment by jjrv** [comment]
For me that code prints `true`, at least using the `develop` branch.

Hopefully I fixed the getter issue just now, `this` was still bound wrong.

**Comment by aksonov** [comment]
Thanks, I will check. Also is it possible to transfer correct param types (I see ‘any’ instead of ‘string’ or ‘number’)?

And another question - how to get environment params? Now I have to use 
`const {provider} = getEnv(self as INodeEntity)`
for all actions...

**Comment by aksonov** [comment]
Still nothing with latest develop branch - either getters and even views:

`TypeError: t.isDone is not a function` for views, and just 'undefined' for getters

**Comment by aksonov** [comment]
```
import {types, flow} from 'mobx-state-tree'
import {mst, shim, action} from 'classy-mst'

const TodoData = types
  .model({
    title: types.string,
    done: false
  })
  .named('TodoData')

class TodoCode extends shim(TodoData) {
  get isDone(): boolean {
    return this.done
  }
  @action
  toggle() {
    this.done = !this.done
  }

  @action
  run() {
    return flow(function*() {
      yield Promise.resolve('This gets lost')
      return 'Returned value'
    })()
  }
}

const Todo = mst(TodoCode, TodoData)
const NewTodoData = Todo.props({count: 0})
class NewTodoCode extends shim(NewTodoData, Todo) {
  @action
  toggle() {
    console.log('Toggled ' + ++this.count + ' times!')
    super.toggle()
  }
}
const NewTodo = mst(NewTodoCode, NewTodoData)
describe('hello', () => {
  it('first', async done => {
    try {
      const t = Todo.create({title: '123'})
      t.toggle()
      console.log(await t.run())
      console.log(t.isDone)
      done()
    } catch (e) {
      done(e)
    }
  })
})
```

**Comment by jjrv** [comment]
I ran your test with Mocha and it prints:

```
  hello
Returned value
true
    1) first


  0 passing (27ms)
  1 failing

  1) hello
       first:
     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at Object.<anonymous> (test/test.js:129:21)
      at step (test/test.js:48:23)
      at Object.next (test/test.js:29:53)
      at fulfilled (test/test.js:20:58)
      at <anonymous>
```

What was the expected output?

**Comment by aksonov** [comment]
It should pass (but for Mocha 2.x), and it returns error/undefined for me (where you see 'true'), develop branch...

**Comment by jjrv** [comment]
It's probably because the TypeScript compiler fails to emit files under `node_modules` so `classy-mst.js` is still based on `master` branch code. You can remove the `files` section from `node_modules/classy-mst/src/tsconfig.json` and run `npm install` again inside `node_modules/classy-mst` or wait for a release. The test seems to work anyway.

**Comment by jjrv** [comment]
You can also try:

```bash
git clone https://gist.github.com/jjrv/3083569f7f57004527096621f42e4571
cd 3083569f7f57004527096621f42e4571
npm install && npm test
```

That will recreate the test setup here.

**Comment by aksonov** [comment]
Thank you, it works. Closing it. Any suggesting about simplifying access to environment variables? Also async syntax is a little be awkward...

**Comment by aksonov** [comment]
I'm running unit tests directly from TypeScript using ts-node and it outputs 'undefined'...

**Comment by aksonov** [comment]
```
node node_modules/mocha/bin/_mocha --timeout 10000 -r ts-node/register test/test.ts 
```

**Comment by jjrv** [comment]
After the latest commit, `getEnv(this)` without any type casts inside methods should now compile without errors.

**Comment by jjrv** [comment]
If you clone my test setup gist and run:

```bash
npm install --save-dev ts-node
npm install
node node_modules/mocha/bin/_mocha --timeout 10000 -r ts-node/register test.ts
```

it seems to work.
