### ISSUE TITLE
Missing getters/setters in inherited models in TypeScript compiled to target ES6, works on ES5.

### ISSUE THREAD

**Issue by dsabanin** [charto/classy-mst#7]
First of all, thanks for the great project! It's amazing how big of a difference it made in our pretty large TypeScript codebase. 

Unfortunately we're seeing an issue when trying to compile to ES6 instead of ES5. It looks like getters and setters are not copied from the ES6 class associated with model when the model is inherited from another model. 

Here's an excerpt of the code:

#### Base model: 

```typescript
const EntityProps = types
  .model('Entity')
  .props<EntitySchema, EntityProps>({
    _id: types.identifier(types.string),
  });

class EntityCode extends shim(EntityProps) implements EphemeralNode {
  get id(): string {
    return this._id;
  }
}

export const Entity = mst(EntityCode, EntityProps, 'Entity');
export type EntityModelDynamic = typeof Entity.Type;
export interface Entity extends EntityModelDynamic {}
```

#### Derived model: 

```typescript
const UserProps = Entity
  .props({
    firstName: types.string,
    lastName: types.string
    email: types.string
  });

class UserData extends shim(UserProps, Entity) {
  get fullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
  get shortName(): string {
    return `${this.firstName} ${this.lastName.charAt(0)}.`;
  }
  @action setEmail(email: string) {
    this.email = email;
  }  
}

export const User = mst(UserData, UserProps, 'User');
export type UserDynamic = typeof User.Type;
export interface User extends UserDynamic {}
```

#### What I'm seeing is this:

```typescript 
const john = User.create({_id: 'abc123', firstName: 'John', lastName: 'Doe', email: ''});
john._id === 'abc123' // works
john.id() === 'abc123' // works
john.setEmail('john@protonmail.com') // works
john.shortName === undefined // does not work
john.fullName === undefined  // does not work
```

Any ideas what this could be? I spent quite some time trying to resolve this, but was not successful.

**Comment by jjrv** [comment]
It seems the base class getter didn't really work either. In your test code you're calling it as a method, not using it as a getter.

The problem was that ES6 defines the getters / setters as non-enumerable and when copied to the model, `mobx-state-tree` doesn't actually see them. After forcing them to be always enumerable, the problem seems to be fixed.

The fix is included in the latest version, 1.0.2.

**Comment by dsabanin** [comment]
Thanks for the fix! I'm going to give it a try right now. Sorry for the broken test code, I had to do it by memory because all my changes were rolled back :) Great job finding it!

**Comment by dsabanin** [comment]
Can confirm now it was fixed! Thank you.
