### ISSUE TITLE
MST 3.0

### ISSUE THREAD

**Issue by dsabanin** [charto/classy-mst#9]
Hey! I just wanted to say again, thanks for the great library, without it, I wouldn't be able to use MST for the size of our project.

Have you considered what would it take to update for MST 3.0 yet? The performance gains and new types are very tempting. I took a quick stab at updating the code myself, but didn't have enough time to get anywhere. 

Is this something you're thinking about working on? If not, I'd appreciate any clues on what you think needs to be updated to get to MST 3.0 support with least changes possible. I don't want to rewrite everything. 

I suspect actually that only types might be affected.

Thank you!

**Comment by ksjogo** [comment]
Would also be interested in having an updated version.

**Comment by jjrv** [comment]
Sorry about the delay! I'll have a fix soon. The functional changes needed are really minor, types are a bigger overhaul.

**Comment by jjrv** [comment]
OK, tests for `classy-mst` 3.0.0 now run successfully with `mobx-state-tree` 3.2.1.

Testing wasn't very extensive yet, but the functional changes were indeed tiny: one handler needed a wrapper object and another had to be attached to a different object. However you might have issues with typings in a larger project... I'd appreciate any reports!

**Comment by jjrv** [comment]
Technically the first generic param is now `PROPS`, and the old `S` is by default `ModelSnapshotType<PROPS>`, sometimes used as the 2nd or 4th parameter: `<C, S, T>` or `<PROPS, OTHERS, C, S, T>`. I renamed all instances of `S` to reflect the change in their semantics.

**Comment by dsabanin** [comment]
This worked great for us, thank you very much for your work!
We hover around 30k LOC, and types were good everywhere except for a few places where we play with MST internals.
